### ISSUE TITLE
Wonder how to draw such a visualization gif

### ISSUE THREAD

**Issue by yzy1996** [SNAS-Series/SNAS-Series#3]
The visualization gif is really cool! 

Could you tell me what software or method you use to make it?

Thank you!

**Comment by HehuiZheng** [comment]
Thank you for your interest in our work. The gif is made by Microsoft Powerpoint. Save the slides as a video clip and it can then be converted to gif either online or with multiple video players.

**Comment by yzy1996** [comment]
Thanks for your reply!
