### ISSUE TITLE
Implementation ERROR when you save alpha_log

### ISSUE THREAD

**Issue by my462** [SNAS-Series/SNAS-Series#6]
Dear auther,
When I try to impletement your method in my own task, I realize you save the model with log_alpha after each epoch finished and you only reset the log alpha with the early stop dictionary at the start of each epcoh. However, the alpha log is changed a lot after you train the whole epoch, and the early stop fixed layers' index may not be consistent with the log alpha after you train the whole epoch. IT means you save the wrong log alpha in your first step and thus choose the wrong path to train in you second step.
Hope to hear from you soon.

**Comment by skhu101** [comment]
Thanks for figuring it out. We have checked about this when we do experiments. Actually, the relative order of log_alpha will not change in one epoch once the log_alpha satisfies the early stop strategy. The reason we do this is to save time. Anyway, you can reset the log_alpha after each iteration. You can also plot the log_alpha curve to check this.

**Comment by my462** [comment]
> Thanks for figuring it out. We have checked about this when we do experiments. Actually, the relative order of log_alpha will not change in one epoch once the log_alpha satisfies the early stop strategy. The reason we do this is to save time. Anyway, you can reset the log_alpha after each iteration. You can also plot the log_alpha curve to check this.

Reseting the log alpha after each iter is what I have done in my task. And the larger and deeper supernet I use or the larger dataset might be the reason why my log alpha changes a lot and can’t remain the relative order after each epoch.
Anyway thanks for sharing your great idea and code!

**Comment by skhu101** [comment]
Thanks for sharing us the details of your experiments! We will change the code to avoid the unnecessary misunderstanding. Hope things go smoothly with your experiments!
