### ISSUE TITLE
questions about equation in paper

### ISSUE THREAD

**Issue by bestfleer** [SNAS-Series/SNAS-Series#9]
Hi, SNAS is really fantastic. I'm following SNAS now. But I cannot understand what the alpha_1^k is in Eq. 28 in the paper. It is grateful if you can explain it to me. 
![21641614921875_ pic_hd](https://user-images.githubusercontent.com/39068182/110071592-45e42980-7db7-11eb-9b13-e4e67ea13d5c.jpg)

**Comment by SRXie** [comment]
Sorry it is a typo. It should be alpha_{i, j}^k, consistent with other lines. Thanks for pointing it out!

**Comment by bestfleer** [comment]
And can you tell me how to obtain line4 from line3 in Eq.28?    Why dU_ij can be replaced by dZ_ij?

**Comment by SRXie** [comment]
It is the change of variable in reparameterization. You can check the original paper of Gumbel-softmax or Concrete distribution for details.
